language: java

jdk:
- openjdk8

branches:
  only:
  - master

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
- zip -r rest-api-with-spring *
- mkdir -p deploy
- mv rest-api-with-spring.zip deploy/rest-api-with-spring.zip

deploy:
- provider: s3
  local_dir: deploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: springboot-webservice-deploy-final
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  wait-until-deployed: true
  on:
    repo: juyoungyoo/spring-boot-rest-api
    branch: master

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify