spring:
  profiles:
    active: local

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app-security:
  admin-username: admin@email.com
  admin-password: admin1
  user-username: user@email.com
  user-password: user1
  client-id: myApp
  client-secret: pass

---
spring:
  profiles: dev
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/colini
    username: friday
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    # PostgreSQL crateClob() error
    jdbc:
      lob:
        non_contextual_creation: true
    # PostgreSQL crateClob() error
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

---
spring:
  profiles: local

  jpa:
    hibernate:
      ddl-auto: create-drop