# Spring boot 지원 object mapper
# object json -> object  변환 (fail)
# 객체 -> json
#spring.jackson.serialization.
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/colini
    username: friday
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    # PostgreSQL crateClob() error
    jdbc:
      lob:
        non_contextual_creation: true
    format_sql: true
    show-sql: true
    open-in-view: false
    # PostgreSQL crateClob() error
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app-security:
  admin-username: admin@email.com
  admin-password: admin
  user-username: user@email.com
  user-password: user
  client-id: myApp
  client-secret: pass